version: '3.8'

services:
  esus-db:
    image: esusdb
    container_name: esus-db
    hostname: esus-db
    environment:
      POSTGRES_DB: esus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: esus
      TZ: America/Sao_Paulo
      LC_ALL: pt_BR.UTF-8
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./backups:/home/esus/backups
    ports:
      - "5433:5432"
    networks:
      - rede-esus
    restart: unless-stopped

  esus-app:
    image: esusapp
    container_name: esus-app
    privileged: true
    hostname: esus-app
    restart: unless-stopped
    command: /lib/systemd/systemd
    ports:
      - "8080:8080"
    networks:
      - rede-esus
    tmpfs:
      - /run
      - /run/lock
      - /run/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./chaves/:/opt/e-SUS/webserver/chaves/:rw
      - ./application.properties:/opt/e-SUS/webserver/config/application.properties:rw
      - ./sistemas/:/home/esus/sistemas/:rw
    environment:
      - TZ=America/Sao_Paulo

networks:
  rede-esus: