version: '3.8'

services:
  esus-db:
    image: esusdb
    container_name: esus-db
    hostname: esus-db
    environment:
      POSTGRES_DB: esus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: esus
      TZ: America/Sao_Paulo
      LC_ALL: pt_BR.UTF-8
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./restaurar_backup.sh:/home/esus/backups/restaurar_backup.sh
      - ./backups:/home/esus/backups
    ports:
      - "5433:5432"
    networks:
      - rede-esus
    restart: unless-stopped

  esus-app:
    image: esusapp
    container_name: esus-app
    privileged: true
    hostname: esus-app
    restart: unless-stopped
    command: >
      bash -c "
      if [ -f /opt/e-SUS/webserver/standalone.sh ]; then
        chmod 777 /opt/e-SUS/webserver/standalone.sh;
      fi
      /lib/systemd/systemd
      "
    cgroup: host
    ports:
      - "8080:8080"
    networks:
      - rede-esus
    tmpfs:
      - /run
      - /run/lock
      - /run/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./chaves/:/opt/e-SUS/webserver/chaves/:rw
      - ./application.properties:/opt/e-SUS/webserver/config/application.properties:rw
      - ./standalone.sh:/opt/e-SUS/webserver/standalone.sh:rw
      - ./anexos/:/home/esus/anexos/:rw
      - ./sistemas/:/home/esus/sistemas/:rw
    environment:
      - TZ=America/Sao_Paulo
  pg_backup:
    image: postgres:9.6
    container_name: esus-bkp
    depends_on:
      - esus-db
    environment:
      TZ: America/Sao_Paulo
    networks:
      - rede-esus
    volumes:
      - ./backups:/backups:rw
      - ./pg_backup.sh:/pg_backup.sh:rw
      - ./pgpass:/root/.pgpass:rw
    entrypoint: ["/bin/bash", "-c"]
    command: "/pg_backup.sh"

networks:
  rede-esus: